export default function ResponseDisplay({ result, error }) {
  if (error) {
    return (
      <div role="alert" style={{ border: '1px solid #c00', padding: '1rem', marginTop: '1rem' }}>
        <strong>Something went wrong:</strong> {error}
      </div>
    )
  }

  if (!result) return null

  const isDemo = result.source === 'demo_mode'

  return (
    <div style={{ border: '1px solid #ccc', padding: '1rem', marginTop: '1rem' }}>
      <div
        data-testid="source-indicator"
        style={{
          display: 'inline-block',
          padding: '0.2rem 0.6rem',
          marginBottom: '0.75rem',
          fontSize: '0.8rem',
          fontWeight: 'bold',
          borderRadius: '4px',
          color: '#fff',
          backgroundColor: isDemo ? '#a35b00' : '#0a7d2c',
        }}
      >
        {isDemo ? 'DEMO MODE - not a real AI response' : 'Generated by Bedrock (Claude)'}
      </div>

      <p>
        <strong>Category:</strong> {result.category}
      </p>

      <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>{result.draft}</pre>

      <p style={{ marginTop: '1rem', fontWeight: 'bold' }}>{result.warning}</p>
    </div>
  )
}
