import { useState, useEffect } from 'react'
import { STATUS_LABEL, URGENCY_COLOR } from '../statusStyles'

export default function TicketDetail({ ticket, processing, error, onProcess, onUpdateDraft, onSetStatus, onArchive }) {
  const [draftText, setDraftText] = useState(ticket?.draft || '')

  useEffect(() => {
    setDraftText(ticket?.draft || '')
  }, [ticket?.id, ticket?.draft])

  if (!ticket) {
    return <p style={{ color: '#666' }}>Select a ticket from the queue to get started.</p>
  }

  const isDemo = ticket.source === 'demo_mode'
  const isProcessing = processing === ticket.id
  const isArchived = ticket.status === 'archived'
  const isNew = ticket.status === 'new'
  const hasBeenProcessed = !isNew && !isArchived

  return (
    <div>
      <h2 style={{ marginBottom: '0.2rem' }}>{ticket.category}</h2>
      <p style={{ color: '#666', fontSize: '0.85rem' }}>Ticket #{ticket.id}</p>

      <div style={{ border: '1px solid #eee', padding: '0.75rem', margin: '0.75rem 0', background: '#fafafa' }}>
        {ticket.message}
      </div>

      {isNew && (
        <button onClick={() => onProcess(ticket.id)} disabled={isProcessing}>
          {isProcessing ? 'Processing...' : 'Process with AI'}
        </button>
      )}

      {error && (
        <div role="alert" style={{ border: '1px solid #c00', padding: '0.75rem', marginTop: '0.75rem' }}>
          <strong>Something went wrong:</strong> {error}
        </div>
      )}

      {hasBeenProcessed && (
        <div style={{ marginTop: '1rem' }}>
          <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.75rem' }}>
            <span
              data-testid="source-indicator"
              style={{
                padding: '0.2rem 0.6rem',
                fontSize: '0.8rem',
                fontWeight: 'bold',
                borderRadius: '4px',
                color: '#fff',
                backgroundColor: isDemo ? '#a35b00' : '#0a7d2c',
              }}
            >
              {isDemo ? 'DEMO MODE - not a real AI response' : 'Generated by Bedrock (Claude)'}
            </span>
            {ticket.urgency && (
              <span
                style={{
                  padding: '0.2rem 0.6rem',
                  fontSize: '0.8rem',
                  fontWeight: 'bold',
                  borderRadius: '4px',
                  color: '#fff',
                  backgroundColor: URGENCY_COLOR[ticket.urgency],
                }}
              >
                Urgency: {ticket.urgency}
              </span>
            )}
            <span
              style={{
                padding: '0.2rem 0.6rem',
                fontSize: '0.8rem',
                borderRadius: '4px',
                border: '1px solid #ccc',
              }}
            >
              AI decision: {STATUS_LABEL[ticket.decision] || ticket.decision}
            </span>
          </div>

          <label htmlFor="draft">Draft response (editable)</label>
          <textarea
            id="draft"
            rows={10}
            style={{ width: '100%', fontFamily: 'inherit' }}
            value={draftText}
            onChange={(e) => setDraftText(e.target.value)}
            onBlur={() => onUpdateDraft(ticket.id, draftText)}
          />

          <p style={{ fontWeight: 'bold' }}>AI-generated draft. Human review required before sending.</p>

          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <button onClick={() => onProcess(ticket.id)} disabled={isProcessing}>
              {isProcessing ? 'Processing...' : 'Re-process with AI'}
            </button>
            {ticket.status !== 'resolved' && (
              <button onClick={() => onSetStatus(ticket.id, 'resolved')}>Approve &amp; mark sent</button>
            )}
            <button onClick={() => onArchive(ticket.id)}>Archive</button>
          </div>
        </div>
      )}

      {isArchived && <p style={{ color: '#666' }}>This ticket is archived.</p>}
    </div>
  )
}
